//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public byte[] img { get; set; }
    
        public virtual CategoriaProductos CategoriaProductos { get; set; }
    }
}
